on: 
  push:
    branches:
      - master
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2.3.2
    - name: Composer Install
      run: composer install --no-dev
    - name: CP ENV
      run: cp .env.ci .env
    - name: Key
      run: php artisan key:generate
    - name: migrate
      run: php artisan migrate:fresh --seed -n --force
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.coolkapada.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /public_html/production.coolkapada.com/
    